import pandas as pd    
import os
import xml.etree.ElementTree as ET
from datetime import datetime
import subprocess
from datetime import datetime

def process_suricata_logs_ID2T(): 
    pd.set_option('future.no_silent_downcasting', True)

    log_file = './logs/eve.json'
    if not os.path.exists(log_file):
        print(f"No alerts generated by suricata")
        return(0,0,0,0,True)
    
    df_suricata = pd.read_json(log_file, lines=True)
    
    df_suricata = df_suricata[df_suricata['event_type'] == 'flow']
    df_suricata["flow_alerted"] = df_suricata["flow"].apply(lambda x: x.get("alerted", False) if isinstance(x, dict) else False)
    df_suricata['start_time'] = df_suricata['flow'].apply(lambda x: x.get('start') if isinstance(x, dict) else None)
    df_suricata['start_time'] = df_suricata['start_time'].apply(lambda x: int(datetime.strptime(x[:19], '%Y-%m-%dT%H:%M:%S').timestamp() + 3600) if pd.notnull(x) else None)

    df_suricata = df_suricata[['src_ip', 'src_port', 'dest_ip', 'dest_port', 'proto','start_time', 'flow_alerted']] 
    df_suricata['proto'] = df_suricata['proto'].str.lower()
    df_suricata["src_port"] = pd.to_numeric(df_suricata["src_port"], errors="coerce").astype("Int64")
    df_suricata["dest_port"] = pd.to_numeric(df_suricata["dest_port"], errors="coerce").astype("Int64")
    df_suricata = df_suricata.drop_duplicates(subset=["src_ip", "src_port", "dest_ip", "dest_port", "proto", "start_time"])

    xml_file = '../traffic_generators/id2t/output/smallFlows_output_labels.xml'
    tree = ET.parse(xml_file)
    root = tree.getroot()

    timestamp_start_str = root.find('.//timestamp_start/timestamp_hr').text
    timestamp_end_str = root.find('.//timestamp_end/timestamp_hr').text
    timestamp_start = int(datetime.strptime(timestamp_start_str.split('.')[0], '%Y-%m-%d %H:%M:%S').timestamp() + 3600)
    timestamp_end = int(datetime.strptime(timestamp_end_str.split('.')[0], '%Y-%m-%d %H:%M:%S').timestamp()+ 3600)

    temp = open(f"./tmp/temp.log", "w")
    err = open(f"./tmp/err.log", "w")
    id2t_pcap = 'traffic_generators/id2t/output/smallFlows_output.pcap'
    cmd = [
        "sudo", 
        "docker", 
        "exec", 
        "zeek-container", 
        "bash", 
        "-c",
        f"cd logs && zeek -C -r ../{id2t_pcap} ../usr/local/zeek/share/zeek/base/protocols/conn" 
    ]

    process = subprocess.Popen(cmd,stdout=temp, stderr=err)
    process.wait()
    conn_log_file = '../zeek/logs/conn.log'

    df_gt = pd.read_csv(conn_log_file, sep='\t', comment='#', low_memory=False)
    cols = df_gt.columns.tolist()

    cols[0] = 'start_time'
    cols[2] = 'src_ip'
    cols[3] = 'src_port'
    cols[4] = 'dest_ip'
    cols[5] = 'dest_port'
    cols[6] = 'proto'
    df_gt.columns = cols

    df_gt = df_gt[["src_ip", "src_port", "dest_ip", "dest_port", "proto", "start_time"]]
    df_gt["start_time"] = df_gt["start_time"].astype(int)
    df_gt['flow_alerted'] = (df_gt['start_time'] >= timestamp_start) & (df_gt['start_time'] <= timestamp_end)



    df_merged = pd.merge(df_gt, df_suricata, how='left', on=['src_ip', 'dest_ip', 'src_port', 'dest_port', 'proto', 'start_time'],suffixes=('_gt', '_suricata'))
    df_merged['flow_alerted_suricata'] = df_merged['flow_alerted_suricata'].fillna(False)

    df_gt.to_csv("./tmp/df_gt.csv", index=False)
    df_suricata.to_csv("./tmp/df_suricata.csv", index=False)
    df_merged.to_csv("./tmp/df_merged.csv", index=False)

    df_tp = df_merged[(df_merged["flow_alerted_gt"] == True) & (df_merged["flow_alerted_suricata"] == True)]
    df_tn = df_merged[(df_merged["flow_alerted_gt"] == False) & (df_merged["flow_alerted_suricata"] == False)]
    df_fp = df_merged[(df_merged["flow_alerted_gt"] == False) & (df_merged["flow_alerted_suricata"] == True)]
    df_fn = df_merged[(df_merged["flow_alerted_gt"] == True) & (df_merged["flow_alerted_suricata"] == False)]
    
    tot_true_pos = tot_false_pos = tot_false_neg = tot_true_neg = 0

    tot_true_pos += len(df_tp)
    tot_false_pos += len(df_fp)
    tot_false_neg += len(df_fn)
    tot_true_neg += len(df_tn)

    return(tot_true_pos, tot_false_pos,tot_false_neg,tot_true_neg, False)
