import pandas as pd
import os
import subprocess

def process_snort_logs_BOTIOT(pcap_file):
    pd.set_option('future.no_silent_downcasting', True)
    pcap_to_gt_map = {
    "../datasets/BOT-IOT/pcap/DDoS/DDoS_HTTP/DDoS_HTTP.pcap": "../datasets/BOT-IOT/ground_truth/DDoS_HTTP.csv",
    "../datasets/BOT-IOT/pcap/DDoS/DDoS_UDP/DDoS_UDP.pcap": "../datasets/BOT-IOT/ground_truth/DDoS_UDP.csv",
    "../datasets/BOT-IOT/pcap/DDoS/DDoS_TCP/DDoS_TCP.pcap": "../datasets/BOT-IOT/ground_truth/DDoS_TCP.csv",

    "../datasets/BOT-IOT/pcap/DoS/DoS_HTTP/DoS_HTTP.pcap": "../datasets/BOT-IOT/ground_truth/DoS_HTTP.csv",
    "../datasets/BOT-IOT/pcap/DoS/DoS_UDP/DoS_UDP.pcap": "../datasets/BOT-IOT/ground_truth/DoS_UDP.csv",
    "../datasets/BOT-IOT/pcap/DoS/DoS_TCP/DoS_TCP.pcap": "../datasets/BOT-IOT/ground_truth/DoS_TCP.csv",
    
    "../datasets/BOT-IOT/pcap/Scan/Service/Service.pcap": "../datasets/BOT-IOT/ground_truth/Service_Scan.csv",
    "../datasets/BOT-IOT/pcap/Scan/OS/OS.pcap": "../datasets/BOT-IOT/ground_truth/OS_Scan.csv",

    "../datasets/BOT-IOT/pcap/Theft/Data_Exfiltration/Data_Exfiltration.pcap": "../datasets/BOT-IOT/ground_truth/Data_exfiltration.csv",
    "../datasets/BOT-IOT/pcap/Theft/Keylogging/keylogging.pcap": "../datasets/BOT-IOT/ground_truth/Keylogging.csv",
    }

    gt_path = pcap_to_gt_map.get(pcap_file) 
    if gt_path:
        chunk_list = []

        for chunk in pd.read_csv(gt_path, delimiter=';', chunksize=100_000):
            chunk_list.append(chunk)

        df_gt = pd.concat(chunk_list, ignore_index=True)
    else:
        print(f"No ground truth found for PCAP: {pcap_file}")
 
    column_mapping = {
    "saddr": "src_ip",
    "sport": "src_port",
    "daddr": "dest_ip",
    "dport": "dest_port",
    "stime" : "start_time",
    "attack": "flow_alerted",
    }

    df_gt.rename(columns=column_mapping, inplace=True)
    df_gt = df_gt[['src_ip', 'src_port', 'dest_ip', 'dest_port', 'proto', 'start_time', 'flow_alerted']]
    df_gt['start_time'] = df_gt['start_time'].astype(str).str.split('.').str[0].astype(int)

    df_gt['flow_alerted'] = df_gt['flow_alerted'].replace({0: False, 1: True})

    df_gt['src_port'] = pd.to_numeric(df_gt['src_port'], errors='coerce').astype('Int64')
    df_gt['dest_port'] = pd.to_numeric(df_gt['dest_port'], errors='coerce').astype('Int64')

    log_file = './logs/alert_csv.txt'

    if not os.path.exists(log_file):
        print(f"No alerts generated by Snort")
        return(0,0,0,0,True)
    column_names = ["timestamp", "pkt_num", "proto", "pkt_gen", "pkt_len", "dir", "src_ap", "dst_ap", "rule", "action", "msg", "class", "start_time"]

    # Load the Snort alert CSV file
    df_snort = pd.read_csv(log_file, names=column_names, header=None)

    # Rename 'action' to 'flow_alerted' and set it to True
    df_snort.rename(columns={'action': 'flow_alerted'}, inplace=True)
    df_snort['flow_alerted'] = True  # Set all values in flow_alerted to True

    # Split 'src_ap' and 'dst_ap' into IP and Port
    df_snort[['src_ip', 'src_port']] = df_snort['src_ap'].str.split(':', n=1, expand=True)
    df_snort[['dest_ip', 'dest_port']] = df_snort['dst_ap'].str.split(':', n=1, expand=True)

    # Convert ports to integers for consistency
    df_snort['src_port'] = pd.to_numeric(df_snort['src_port'], errors='coerce').astype("Int64")
    df_snort['dest_port'] = pd.to_numeric(df_snort['dest_port'], errors='coerce').astype("Int64")
    df_snort['src_ip'] = df_snort['src_ip'].str.strip()
    df_snort['dest_ip'] = df_snort['dest_ip'].str.strip()
    df_snort['proto'] = df_snort['proto'].str.strip().str.lower()

    # Keep only the necessary columns
    df_snort = df_snort[['src_ip', 'src_port', 'dest_ip', 'dest_port', 'proto', 'start_time', 'flow_alerted']]  # Keep only necessary columns
    df_snort = df_snort.drop_duplicates(subset=["src_ip","src_port", "dest_ip", "dest_port", "proto", "start_time"])
    
    # Using zeek here to extract all the flows from the pcap file since snort only logs alerts and not also benign flows
    temp = open(f"./tmp/temp.log", "w")
    err = open(f"./tmp/err.log", "w")
    cmd = [
        "sudo", 
        "docker", 
        "exec", 
        "zeek-container", 
        "bash", 
        "-c",
        f"cd logs && zeek -C -r ../{pcap_file} ../usr/local/zeek/share/zeek/base/protocols/conn" 
    ]

    process = subprocess.Popen(cmd,stdout=temp, stderr=err)
    process.wait()
    zeek_flows = '../zeek/logs/conn.log'


    df_zeek_flows = pd.read_csv(zeek_flows, sep='\t', comment='#', low_memory=False)
    cols = df_zeek_flows.columns.tolist()

    cols[0] = 'start_time'
    cols[2] = 'src_ip'
    cols[3] = 'src_port'
    cols[4] = 'dest_ip'
    cols[5] = 'dest_port'
    cols[6] = 'proto'
    df_zeek_flows.columns = cols

    df_zeek_flows = df_zeek_flows[["src_ip", "src_port", "dest_ip", "dest_port", "proto", "start_time"]]
    df_zeek_flows["start_time"] = df_zeek_flows["start_time"].astype(int)

    df_snort = pd.merge(df_zeek_flows, df_snort, how='left', on=['src_ip','src_port','dest_ip','dest_port','proto', 'start_time'],suffixes=('_zeek_flows', '_snort'))
    
    df_merged = pd.merge(df_gt, df_snort, how='inner', on=['src_ip','src_port','dest_ip','dest_port','proto', 'start_time'],suffixes=('_gt', '_snort'))
    df_merged['flow_alerted_snort'] = df_merged['flow_alerted_snort'].fillna(False)
    
    df_gt.to_csv("./tmp/df_gt.csv")
    df_snort.to_csv("./tmp/df_snort.csv")
    df_merged.to_csv("./tmp/df_merged.csv")
    
    df_tp = df_merged[(df_merged["flow_alerted_gt"] == True) & (df_merged["flow_alerted_snort"] == True)]
    df_tn = df_merged[(df_merged["flow_alerted_gt"] == False) & (df_merged["flow_alerted_snort"] == False)]
    df_fp = df_merged[(df_merged["flow_alerted_gt"] == False) & (df_merged["flow_alerted_snort"] == True)]
    df_fn = df_merged[(df_merged["flow_alerted_gt"] == True) & (df_merged["flow_alerted_snort"] == False)]
    
    tot_true_pos = tot_false_pos = tot_false_neg = tot_true_neg = 0

    tot_true_pos += len(df_tp)
    tot_false_pos += len(df_fp)
    tot_false_neg += len(df_fn)
    tot_true_neg += len(df_tn)    
    return(tot_true_pos, tot_false_pos,tot_false_neg,tot_true_neg, False)


