import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "Attack": ["Port Scan", "EternalBlue", "SQLi", "DDoS"],
    "Suricata": [0.39, 0.9023, 0.9465, 0.8314],
    "Snort": [0.3876, 0.8981, 0.6175, 0.8486],
    "Zeek": [0.3788, 0.924, 0.7218 , 0.821],
}

df = pd.DataFrame(data)

# Convert to percentage
df["Suricata"] = df["Suricata"] * 100
df["Snort"] = df["Snort"] * 100
df["Zeek"] = df["Zeek"] * 100

indices = np.arange(len(df["Attack"]))
bar_width = 0.25

# Plot bars
plt.bar(indices - bar_width, df["Suricata"], width=bar_width, label="Suricata")
plt.bar(indices, df["Snort"], width=bar_width, label="Snort")
plt.bar(indices + bar_width, df["Zeek"], width=bar_width, label="Zeek")

# Labeling
plt.xlabel("Attack Type")
plt.ylabel("Accuracy (%)")
plt.xticks(indices, df["Attack"], rotation=90)
plt.yticks(np.arange(0, 110, 10))  # Set y-axis ticks at 10% intervals
plt.title("NIDS Accuracy by Attack Type generated by ID2T")
plt.legend()
plt.tight_layout()
plt.show()
# Save figure
# plt.savefig("img/nids_fpr_by_attack.png")
